#define WINDOW_WIDTH 700
#define WINDOW_HEIGHT 700


/**
 * PRISON DUNGEON WORLD SETTINGS
*/
#define PRISON_MAP_WIDTH 50
#define PRISON_MAP_HEIGHT 50
#define PRISON_MIN_ROOM_WIDTH 3
#define PRISON_MIN_ROOM_HEIGHT 3
#define PRISON_MAP_BSP_ITERATIONS 3